# Config for Dependabot updates. See Documentation here:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Update GitHub actions in workflows
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'

  # Enable version updates for Docker - Django containers
  - package-ecosystem: 'docker'
    directory: '/deploy/local/compose/django/'
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'
          - 'version-update:semver-minor'

  - package-ecosystem: 'docker'
    directory: '/deploy/production/compose/django/'
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'
          - 'version-update:semver-minor'

  # Enable version updates for Docker - Vue containers
  - package-ecosystem: 'docker'
    directory: '/deploy/local/compose/vue/'
    schedule:
      interval: 'daily'

  # Enable version updates for Docker - Other containers
  - package-ecosystem: 'docker'
    directory: '/deploy/local/compose/postgres/'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'docker'
    directory: '/deploy/local/compose/minio/'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'docker'
    directory: '/deploy/local/compose/minio/mc/'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'docker'
    directory: '/deploy/production/compose/postgres/'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'docker'
    directory: '/deploy/production/compose/nginx/'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'docker'
    directory: '/deploy/production/compose/aws/'
    schedule:
      interval: 'daily'

  # Enable version updates for Python/Pip
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'daily'

  # Enable version updates for npm packages in Vue app
  - package-ecosystem: 'npm'
    directory: '/web'
    schedule:
      interval: 'daily'
