# .github/dependabot.yml
# Config for Dependabot updates. See Documentation here:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Update GitHub actions in workflows
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      github-actions:
        patterns:
          - '*'

  # Enable version updates for Docker - Django containers
  - package-ecosystem: 'docker'
    directories:
      - '/deploy/local/compose/django/'
      - '/deploy/production/compose/django/'
    schedule:
      interval: 'monthly'
    # Ignore minor version updates (3.10 -> 3.11) but update patch versions
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'
          - 'version-update:semver-minor'
    groups:
      docker-python:
        patterns:
          - '*'

  # Enable version updates for Docker - Vue containers
  - package-ecosystem: 'docker'
    directory: '/deploy/local/compose/vue/'
    schedule:
      interval: 'monthly'

  # Enable version updates for Docker - Other containers
  - package-ecosystem: 'docker'
    directories:
      - '/deploy/local/compose/postgres/'
      - '/deploy/production/compose/postgres/'
      - '/deploy/production/compose/nginx/'
      - '/deploy/production/compose/aws/'
    schedule:
      interval: 'monthly'
    groups:
      docker-infrastructure:
        patterns:
          - '*'

  # Enable version updates for Python/Pip
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      python:
        update-types:
          - 'minor'
          - 'patch'

  # Enable version updates for npm packages in Vue app
  - package-ecosystem: 'npm'
    directory: '/web'
    schedule:
      interval: 'monthly'
    ignore:
      - dependency-name: 'node'
        update-types:
          - 'version-update:semver-major'
      - dependency-name: 'vue'
        update-types:
          - 'version-update:semver-major'
