# deploy/local/web.yml
name: django_hans_local

volumes:
  node_modules: {}
  postgres_data: {}
  postgres_data_backups: {}
  minio_data: {}
  redis_data: {}

services:
  django:
    build:
      context: ../..
      dockerfile: ./deploy/local/compose/django/Dockerfile
    image: django
    container_name: django
    depends_on:
      - postgres
      - redis
      - minio
    volumes:
      - ../..:/app:z
    env_file:
      - ./.envs/.django
    ports:
      - "8000:8000"
    command: /start

  vue:
    build:
      context: ../..
      dockerfile: ./deploy/local/compose/vue/Dockerfile
    image: vue
    container_name: vue
    volumes:
      - type: bind
        source: ../../web
        target: /app
      - type: volume
        source: node_modules
        target: /app/node_modules
    env_file:
      - ./.envs/.vue
    ports:
      - "5173:5173"
    depends_on:
      - django
    command: /start

  postgres:
    build:
      context: ../..
      dockerfile: ./deploy/production/compose/postgres/Dockerfile
    image: postgres
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_data_backups:/backups
    env_file:
      - ./.envs/.postgres

  minio:
    build:
      context: ../..
      dockerfile: ./deploy/local/compose/minio/Dockerfile
    image: minio
    container_name: minio
    volumes:
      - minio_data:/data
    env_file:
      - ./.envs/.minio
    ports:
      - "9000:9000"
      - "9001:9001"

  redis:
    image: docker.io/redis:8
    container_name: redis
    volumes:
      - redis_data:/data

  celery_worker:
    build:
      context: ../..
      dockerfile: ./deploy/local/compose/django/Dockerfile
    image: celery_worker
    container_name: celery_worker
    depends_on:
      - redis
      - postgres
    volumes:
      - ../..:/app:z
    env_file:
      - ./.envs/.django
    command: /start-celery-worker

  celery_beat:
    build:
      context: ../..
      dockerfile: ./deploy/local/compose/django/Dockerfile
    image: celery_beat
    container_name: celery_beat
    depends_on:
      - redis
      - postgres
    volumes:
      - ../..:/app:z
    env_file:
      - ./.envs/.django
    command: /start-celery-beat

  flower:
    build:
      context: ../..
      dockerfile: ./deploy/local/compose/django/Dockerfile
    image: flower
    container_name: flower
    depends_on:
      - redis
      - postgres
    volumes:
      - ../..:/app:z
    env_file:
      - ./.envs/.django
    ports:
      - '5555:5555'
    command: /start-flower
