#!/bin/bash
# deploy/production/compose/django/start

set -o errexit
set -o pipefail
set -o nounset

python /app/manage.py collectstatic --noinput

exec gunicorn config.asgi:application \
  --bind 0.0.0.0:8000 \
  --chdir=/app \
  --worker-class uvicorn.workers.UvicornWorker
