#!/bin/bash
# deploy/local/compose/django/start

set -o errexit
set -o pipefail
set -o nounset

# Running migration before starting up the server
# is only added as a utility for development.
python /app/manage.py migrate

# Start the server with uvicorn
exec uvicorn config.asgi:application --host 0.0.0.0 --port 8000 --reload --reload-include '*.html'
